#src
Import('env')

grk_env = env.Clone()
grk_env.Append()
grk_env.GLSL('shaders')

def objs(e, name, src):
	return [e.Object('%s_%s.o'%(name, x), x+'.c') for x in src]

base_src = ['gl', 'math', 'logging','glmath', 'orbital', 'trades', 'function']

exe1 = grk_env.Program('kerbie', objs(grk_env, 'grk', base_src + ['main']), LIBS=['m', 'gmp', 'GLESv2', 'glfw'])
